server.port=8085
spring.application.name=Spring-Batch-Demo

# Spring Batch DataSource configuration
spring.datasource.url=jdbc:mysql://localhost:3306/spring_batch_db
spring.datasource.username=root
spring.datasource.password=system@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#batch se related  agar kuch configurations
spring.batch.jdbc.initialize-schema=always

spring.sql.init.mode=always

#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=none

